#define ENABLE_BRAVE_CAPE_WITH_MONEY

#ifdef ENABLE_BRAVE_CAPE_WITH_MONEY
    #define EFFECT_BRAVE_CAPE
    #define BUFF_RAGE_BRAVE_CAPE
    #define ENABLE_RANGE_MONSTER_BRAVE_CAPE
    #define LEVEL_LIMIT_FOR_TAX_PER_USE
#endif
